### ISSUE TITLE
GZIP files compatibility

### ISSUE THREAD

**Issue by Katsileros** [deeplab-ai/deephub#15]
This feature requires from the framework to be able to read gzipped tfrecord files. This means that both the feeders and the tf_record metadata functionality must be able to handle this kind of compressed files. 

For example, the solution for the feeder is a flag in TFRecordDataset like this:
- TFRecordDataset(filenames, "GZIP" or " ") in case of GZIP or no compression.

This functionality must also be supported in order to extract the json metadata file.

@nanton96 I will send you a gzipped file to use it as your test case in order to implement this feature.

**Comment by nanton96** [comment]
I have made a pull request which adds this functionality #16
